#!/usr/bin/env bash
HEAD
# kills the infinity and beyond  program using sigkill signal

# Terminate the infinate process
pkill -15 "bash ./4-to_infinity_and_beyond" -f
# Bash script that stops '4-to_infinity_and_beyond' process
# Requirement:
#	-You cannot use 'kill' or 'killall'

pkill -f 4-to_infinity_and_beyond

 7b70f209480ef2e15b0ae5b340c62b66bc33dac8
