#!/usr/bin/env bash
# This script reads and formats user information from /etc/passwd

# Set IFS to ':' to split fields in /etc/passwd
IFS=":"

# Read each line of /etc/passwd
while read -r username password uid gid comment home shell; do
  # Display the formatted output
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $comment"
done < /etc/passwd
