#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using an until loop

count=1
until [ $count -gt 10 ]  # The loop continues until count is greater than 10
do
    echo "Best School"
    count=$((count + 1))  # Increment the count
done

