#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with special messages for the 4th, 9th, and 17th iterations

count=1
while [ $count -le 20 ]
do
    echo "$count"
    case $count in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    count=$((count + 1))
done
