#!/usr/bin/env bash
#This is a script displays a list of currently running processes.
#Must show all processes, for all users, including those which might not have a TTYY
#Display a useer oriented format.
#Show process hierachy

ps -a -x -u -f
