#!/usr/bin/env bash

while true; do
    echo "To infinity and beyond"
    sleep 1
    
    if [ -f /tmp/stop_signal ]; then
        echo "Terminated"
        rm /tmp/stop_signal
        break
    fi
done

